version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  front:
    image: 41px/cp2ville 
    depends_on:
      - db
    command: /usr/local/bin/cp2ville
    ports:
      - "3000:3000"
