version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  front:
    image: 41px/cp2ville 
    depends_on:
      - db
    command: cp2ville
    ports:
      - "3000:3000"
